name: Publish Docker image

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  push_to_ghcr:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - uses: firehed/multistage-docker-build-action@v1
        id: build-problem1
        with:
          repository: ghcr.io/lorne-luo/code_kata
          stages: base, problem1, problem2
          server-stage: problem1

      - uses: firehed/multistage-docker-build-action@v1
        id: build-problem2
        with:
          repository: ghcr.io/lorne-luo/code_kata
          stages: base, problem2
          server-stage: problem2